variables:
  CI_REGISTRY: docker.io
  CI_REGISTRY_USER: pbaitule
  CI_REGISTRY_IMAGE: index.docker.io/pbaitule/basic-nginx-webserver

stages:
  - build
  - push

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" ./app/

push:
  stage: push
  script:
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
